POST http://localhost:5000/api/skills
Content-Type: application/json

{
    "name": "HTML"
}

###

GET http://localhost:5000/api/skills

###

DELETE http://localhost:5000/api/skills
Content-Type: application/json

{
    "idToDelete": 1
}

###

PUT http://localhost:5000/api/skills
Content-Type: application/json

{
    "id": 2,
    "name": "new name"
}