POST http://localhost:3000/api/wilders
Content-Type: application/json

{
    "name": "lorem",
    "description": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." 
}

###

GET http://localhost:3000/api/wilders

###

DELETE http://localhost:3000/api/wilders
Content-Type: application/json

{
    "idToDelete": 1
}

###

PUT http://localhost:3000/api/wilders
Content-Type: application/json

{
    "id": 1,
    "name": "louis",
    "description": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

###

POST http://localhost:3000/api/wilders/addSkill
Content-Type: application/json

{
    "wilderName": "quentin",
    "skillName": "Javascript"
}