POST http://localhost:3000/api/wilders
Content-Type: application/json

{
    "name": "Rest Client wilder"
}

###

GET http://localhost:3000/api/wilders

###

DELETE http://localhost:3000/api/wilders
Content-Type: application/json

{
    "idToDelete": 1
}

###

PUT http://localhost:3000/api/wilders
Content-Type: application/json

{
    "id": 2,
    "name": "new name"
}

###

POST http://localhost:3000/api/wilders/addSkill
Content-Type: application/json

{
    "wilderName": "new name",
    "skillName": "Javascript"
}